
on: 
  release:
    types: [created]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: altipla-consulting/altipla.actions/go-release-1.14@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
